### ISSUE TITLE
Wrong content type returned by driver

### ISSUE THREAD

**Issue by BernhardFuchs** [KILTprotocol/kilt-did-driver#18]
The driver is returning content type `text/html` but should return `application/did+ld+json`.  
See the [docs](https://github.com/decentralized-identity/universal-resolver/blob/main/docs/driver-development.md#driver-interface) for clarification

**Comment by Diiaablo95** [comment]
Hello @BernhardFuchs, thanks for pointing it out! We are in the middle of refactoring our DID support, and will update the universal resolver adapter right after that.

**Comment by Diiaablo95** [comment]
@BernhardFuchs we have just released a new version of the driver, [v2.1.0](https://github.com/KILTprotocol/kilt-did-driver/releases/tag/2.1.0) and opened a [PR](https://github.com/decentralized-identity/universal-resolver/pull/266) for the DIF Universal Resolver. I think the issue you highlighted is fixed now, do you mind checking it so that we can close this issue?
